version: '3.8'

services:
  frontend:
    build:
      context: ./dupe-finder-ui
    container_name: dupe-finder-frontend
    ports:
      - "4200:80" # serve compiled app on host:4200 -> container:80 (nginx)
    environment:
      - API_BASE_URL=http://host.docker.internal:8080
      - WS_BASE_URL=ws://host.docker.internal:8080
      - STATIC_CONTENT_URL=http://static-server
    depends_on:
      - static-server
    networks:
      - dupe-finder-network

  static-server:
    image: nginx:alpine
    container_name: dupe-finder-static
    volumes:
      - ${HOME}/dup_files/static_content:/usr/share/nginx/html:ro
    ports:
      - "8085:80"
    networks:
      - dupe-finder-network

networks:
  dupe-finder-network:
    driver: bridge
